-- AlterTable
ALTER TABLE `Post` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `likes` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `User` MODIFY `rank` VARCHAR(191) NOT NULL DEFAULT 'bronze',
    MODIFY `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
